sudo: required
services:
  - docker
before_install:
  - docker build -t ksdev82/docker-react-app -f Dockerfile.dev .
scripts:
  - docker run ksdev82/docker-react-app npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "name of your app"
  env: "Docker-env"
  bucket_name: "name of the bucket"
  bucket_path: "path to the bucket"
  on:
    branch: master
